; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+7 on Thu Apr 28 2022 23:16:08 GMT-0300 (Horário Padrão de Brasília)
M280 P0 S90 ; retract BLTouch

