; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+7 on Thu Apr 28 2022 23:16:10 GMT-0300 (Horário Padrão de Brasília)
; Wait for set temperatures to be reached
M116 P0

